### PR TITLE
Make socket connection GC durable

### PR DESCRIPTION
**Pull request by fenrir-naru**
This is patch for making socket connection more durable for GC cleanup.
When large objects are treated, socketConnection may be unintentionally closed by GC with warning "closing unused connection".
In order to solve this issue, I propose that socketConnection and server_socket.accept will be invoked per each action in R and Ruby sides, respectively.

### CODE REVIEW

**Comment by clbustos** [comment]
Could be set this behavior with an option? Like the permanent flag on db connection

**Comment by fenrir-naru** [comment]
@clbustos Thank you for your advise.
I am planning to implement my new proposal as an option, and I will leave your original persistent connection the default and improve it in case unintentional GC cleanup such as my situation.
I know your original one is superior in terms of speed, however, currently I am in a trouble to detect and recover connection lost on your original one. I need more time to fix it, so please leave open this PR for a while.

**Comment by fenrir-naru** [comment]
@clbustos I have updated this PR to implement the connection reusable mode as the default.
My old implementation with which socket connection is generated every transaction is also activated when the "persistent" option  is false.
Please check.

**Comment by clbustos** [comment]
I will check it. Thanks for the effort!

**Pull request merged**
